### ISSUE TITLE
JustABattery failed to load

### ISSUE THREAD

**Issue by schwabe93** [canitzp/JustABattery#10]
Hey,

i`ve downloaded JustABattery and SolarHelmet and with both mods this Error came up:
 

Failed to create mod instance. ModID: justabattery, class de.canitzp.justabattery.JustABattery

java.lang.NoSuchFieldError: CREATIVE_MODE_TAB
[latest.log](https://github.com/canitzp/JustABattery/files/11916744/latest.log)
[crash-2023-06-30_15.26.40-fml.txt](https://github.com/canitzp/JustABattery/files/11916745/crash-2023-06-30_15.26.40-fml.txt)

**Comment by canitzp** [comment]
Thanks for reporting. This issue is known and will be fixed. Try the download from Modrinth, there it works fine

**Comment by schwabe93** [comment]
Thanks for the Info, the Modrinth Version works. Thanks

**Comment by canitzp** [comment]
curseforge version does work now too
