### ISSUE TITLE
[Suggestion] Configuration option to make batteries charged on craft

### ISSUE THREAD

**Issue by UplinkPhobia** [canitzp/JustABattery#11]
It would be a nice feature to be able to have charged batteries right away, without requiring another system to charge them. In mods where electricity production can be complicated, batteries could become a sort of "early" source of electricity.
Considering that batteries require a block of redstone that is electrically "active", it even fits the logic of the game; and if it's an optional feature it shouldn't cause any problems.

**Comment by canitzp** [comment]
Sorry for the late reply.
This is indeed a good idea and easily possible. I'll add this feature soon and release it for 1.19.2 and 1.20.1

**Comment by canitzp** [comment]
The request was added and released with version 43.1.0 for 1.19.2 and 47.1.0 for 1.20.1
