### ISSUE TITLE
[Suggestion] Take charge/extract energy out of an block

### ISSUE THREAD

**Issue by canitzp** [canitzp/JustABattery#3]
Maybe when right clicking the block, but how much?

Idea by **OctupleCompressedCAT**

**Comment by markygnlg** [comment]
Maybe make it customisable in the config for either:
1. "maximum" - max amount battery can take until full or that remains in targeted block;
2. "percentage" preset - just like in your SolarHelmet config ("1.0 is equal to 100% energy", "0.5 is equal to 50%");
3. "fixed" preset amount - can be limited (like in 'solarhelmet-common.toml' [ 0.0 ~ 1000000.0 ]) or unlimited (like in 'justabattery.json')

I'm just following your ideas - simple & easily changed as often as I want!!

**Comment by markygnlg** [comment]
... or a 4th option similar to the "battery_transfer" option:
4. preset "transfer speed" but must hold down a keybind/mousebutton for the transfer to happen;
...

**Comment by canitzp** [comment]
Yeah config options would be great, but in this case I probably use the already existing transfer rate, which is influenced by the "trace width" attribute of the battery.
My idea was that the extraction takes place when you sneak+right click on an energy containing block. It tries to extract as much as it can per click on the block. This value is influenced by the blocks maximum allowed transfer rate and the batteries one.

**Comment by canitzp** [comment]
@markygnlg with the last commit I introduced this new feature and also wrote the corresponding description. You can look at it right here https://github.com/canitzp/JustABattery/blob/master/README.md#extracting-from-blocks and it would be cool if you can let me know your opinion of it.

**Comment by markygnlg** [comment]
Sounds great, as for me testing it, sorry but I'm on 1.16.
