### ISSUE TITLE
1.16.5 fatal bug

### ISSUE THREAD

**Issue by SpoilersMC** [canitzp/JustABattery#5]
Mod causes server/client dimension desynch when moving back to the overworld from a different dimension when in multiplayer on mod version 1.2.0 for 1.16.5 due to recipe injection- same thing that causes create ponder to crash in multiplayer as mentioned on curseforge
this is the fatal error seen on the connecting client upon re-entering the overworld:
[JustABug.txt](https://github.com/canitzp/JustABattery/files/7992251/JustABug.txt)
mod version 1.2.0
minecraft 1.16.5
forge 36.2.26
i know you marked the mod as unsupported for 1.16 but this issue effectively makes the mod unusable.

**Comment by canitzp** [comment]
Fixed with version 36.0.0
