### ISSUE TITLE
Suggestion : Add support for curios api

### ISSUE THREAD

**Issue by RuggedTime** [canitzp/JustABattery#8]
https://www.curseforge.com/minecraft/mc-mods/curios 
Players can save backpack space...Isn't that wonderful？
Just like batterys in Powah mod：https://www.curseforge.com/minecraft/mc-mods/powah

**Comment by canitzp** [comment]
Good suggestion,
In theory I now added the ability to put the batteries inside any curios slot, but I don't create my own, so relying on other mods doing that and I also don't know if the battery does work as expected in this slot. Like for discharging the battery needs to tick, which it does in inventory. Also most most won't charge the battery, while it is in this slot, like my other mod SolarHelmet, only searches through the player inventory, for something to charge and the curios slots aren't part of the inventory.

What are your thoughts about that?

**Comment by RuggedTime** [comment]
I think this might not be a big problem...Because I know there are some mods can charge or discharge items in curios slot ( eg. Botania mod for minecraft 1.18 and the item's ID is mana_ring) .
But I haven't written any mod, all my thoughts are just speculation.
@_@

**Comment by canitzp** [comment]
Well I gonna add the feature, that allows the placement of batteries in the curious slots, but I now have tested it and I can't find a easy way to charge the batteries, while they are in these slots. Other batteries can't charge them and also my other mod "Solar Helmet".

**Comment by canitzp** [comment]
Closed with Just A Battery version 40.1.0
